### ISSUE TITLE
Any outstanding Java issues?

### ISSUE THREAD

**Issue by IanMayo** [open-dis/open-dis-java#1]
Hi there,
it would appear there aren't any outstanding Java issues.  Is there a record on any? Or a wish list?

I may have effort available to move open-dis-java forward, particularly if there are issues/tasks that would also being benefit to my users.

**Comment by mcgredonps** [comment]
The Java version checked in here is a bit of a mess right now-tried to fix some things in the protocol generation and broke everything. The sourceforge release is in better shape. 

I need to back out the changes I made and get closer to right. There are some well known limitations, mainly in the areas that require variable length lists with padding to a byte boundary.

**Comment by leif81** [comment]
I too am keen to help out with the library, especially now that it's on github and we can submit pull requests! :smiley: This is a dream.

@mcgredonps Will you have a chance to resolve the protocol generation issues on the master branch soon? I feel like I should wait for that to happen before submitting some of the issues I've seen.

**Comment by mcgredonps** [comment]
I’ve just set up an open-dis organization at github to host the
repositories.

https://github.com/open-dis

Right now it’s just got the XMLPG protocol generator. I’ll check in the other
repos as I get a chance. It seems like a better way to group the repos than
under my user account.

Leif, I’ve sent you an invite as an admin.

I’ve modified the XMLPG for C# some to remove some MS-Net specific
features. The Unity game engine C# implementation seems to be missing some features
supplied by MS, such as XML marshaling. There’s also some support
for bit fields in there.




On Jan 22, 2016, at 6:51 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


I too am keen to help out with the library, especially now that it's on github and we can submit pull requests! [:smiley:]  This is a dream.

@mcgredonps<https://github.com/mcgredonps> Will you have a chance to resolve the protocol generation issues on the master branch soon? I feel like I should wait for that to happen before submitting some of the issues I've seen.

**Comment by leif81** [comment]
Terrific, thank you Don. I have received the invite and accepted it. I'm
 looking forward to coordinating with you.

**Comment by leif81** [comment]
@mcgredonps This and other of your repositories can be moved over to to the open-dis organization pretty easily so that existing issues and PR's don't get lost. Go to the _Settings -> Transfer ownership_

BTW, speaking of the open-dis github organization, you may have noticed I've updated a couple settings; the logo, description and the web site link. At some point moving the open-dis website over to the github organization would probably make good sense too. See https://pages.github.com

**Comment by IanMayo** [comment]
There are some well known limitations, mainly in the areas that 
    require variable length lists with padding to a byte boundary.

I expect to be receiving DIS message from a CPP implementation fairly soon.  I hope to be able to do some variable length list debugging for this Java implementation when that happens.

Closing issue, to keep repo clean.
