### ISSUE TITLE
Remove unused jars

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-java#13]
I have a hunch most of the jars in the `lib` dir are from older examples and from a time when hibernate and jaxb was supported.

I'm thinking even xmlpg could be built as needed from it's source code instead of keeping a copy in there.

If the Maven pom.xml is a good indication of what's really needed, then everything aside from dis-enums, srm and junit 4.12 can be removed.

**Comment by leif81** [comment]
My mistake, we still use jaxb right?

**Comment by leif81** [comment]
@mcgredonps I need to show you the merits of Netbeans + Maven. Having to maintain two build systems, Ant and Maven, isn't too much fun, lol.

**Comment by leif81** [comment]
Hmm ya I'm confused about jaxb. The annotation's on the generated pdu's are gone, but some of the classes that expected them are still there. e.g. `MarshalExample`, `LogReplay`, `LogWriter.java`.

@mcgredonps What's the plan for jaxb? Is it being dropped? I'd be fine with that.

**Comment by mcgredonps** [comment]
It should be safe to drop it. It was only in there for java-to-xml-and-back, and I think all of that has been rolled into the mainline JDK release anyway.
