### ISSUE TITLE
Add support for Travis CI

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-java#15]
I think it'd be useful to start using [Travis CI](https://travis-ci.org/) to run our build and unit tests on every push for us. It can also build any PR branches to ensure we aren't unknowingly merging broken code.

I think the only changes required will be:
* giving Travis CI access to the project to watch for pushes
* creating a `.travis.yml` config file in the root of the project to tell Travis how to build the project (I'll make a PR for that once I figured that out)

**Comment by mcgredonps** [comment]
I was just looking at that the other night. We’ve used Jenkins in the past but
Travis seems to be the way to go on Github.

On Feb 16, 2016, at 8:30 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


I think it'd be useful to start using Travis CI<https://travis-ci.org/> to run our build and unit tests on every push for us. It can also build any PR branches to ensure we aren't unknowingly merging broken code.

I think the only changes required will be:

  *   giving Travis CI access to the project to watch for pushes
  *   creating a .travis.yml config file in the root of the project to tell Travis how to build the project (I'll make a PR for that once I figured that out)

**Comment by leif81** [comment]
Ya I use a very large Jenkins instance in my company too. It works great for us. But ya for github projects Travis CI seems to have nice benefits, like setup and integration being pretty easy.
