### ISSUE TITLE
VariableParameter has no way of extracting the data

### ISSUE THREAD

**Issue by psylsph** [open-dis/open-dis-java#161]
I'm trying to use the VariableParameter field within the EntityStatePdu to transmit some addition data, I'm send via the Open Dis Python which supports adding the additional data, however there doesn't seem to be a way to extract the data at the receiving end that is written in Java or am I missing something?

**Comment by psylsph** [comment]
I've just noticed it seemed to be implemented https://github.com/open-dis/opendis7-java/blob/master/src-generated/edu/nps/moves/dis7/pdus/VariableParameter.java already so maybe it could be merged across.

**Comment by leif81** [comment]
The dis7 implementation has a getter. Is this what you're after? Or are you using dis6?

https://github.com/open-dis/open-dis-java/blob/master/src%2Fmain%2Fjava%2Fedu%2Fnps%2Fmoves%2Fdis7%2FEntityStatePdu.java#L237

**Comment by psylsph** [comment]
Thanks, looking further into the VariableParameters in the Java implementation I've realized it can't hold the type I want to use anyway, so thanks
