### ISSUE TITLE
disenum dependency in maven

### ISSUE THREAD

**Issue by mcgredonps** [open-dis/open-dis-java#20]
Looks like there's a missing dependency for disenum.jar  in the pom.xml file.

**Comment by leif81** [comment]
Hmm what's the error you're seeing?

This is how the `dis-enums-1.1.jar` is defined as a compile and run time dependency in the `pom.xml`

```
        <dependency>
            <groupId>edu.nps.moves</groupId>
            <artifactId>dis-enums</artifactId>
            <version>1.1</version>
        </dependency>
```

**Comment by mcgredonps** [comment]
Hmm, it appears to be a netbeans problem—for some reason Netbeans isn’t picking it up,
or the SRM jar.

On Feb 29, 2016, at 9:44 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm what's the error you're seeing?

This is how the dis-enums-1.1.jar is defined as a compile and run time dependency in the pom.xml

        <dependency>
            <groupId>edu.nps.moves</groupId>
            <artifactId>dis-enums</artifactId>
            <version>1.1</version>
        </dependency>

**Comment by leif81** [comment]
Silly question, but is the PC you're running Netbeans on connected to the internet?

Because what's happening is Netbeans is trying to fulfill those dependencies by fetching them from Maven Central auto-magically. (And then it caches them locally in your home dir in `~/.m2/repository`)

http://search.maven.org/#artifactdetails%7Cedu.nps.moves%7Cdis-enums%7C1.1%7Cjar

**Comment by leif81** [comment]
@mcgredonps Ever figure this one out?

**Comment by leif81** [comment]
@mcgredonps can we close this one?

**Comment by mcgredonps** [comment]
Fine by me; go ahead and filip it off if you like. I’m busy on some other stuff
right now.
On Jul 10, 2017, at 9:31 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcgredonps<https://github.com/mcgredonps> can we close this one?

**Comment by mcgredonps** [comment]
I was messig around wth that a little, and apparently it relied on another source for the
version number release. Hadn’t figured it all out. Where is the 1.1 code acutally come from?

It’s not using the 1.1 jar file in the lib directory, I’m pretty certain.

On Feb 29, 2016, at 9:44 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm what's the error you're seeing?

This is how the dis-enums-1.1.jar is defined as a compile and run time dependency in the pom.xml

        <dependency>
            <groupId>edu.nps.moves</groupId>
            <artifactId>dis-enums</artifactId>
            <version>1.1</version>
        </dependency>

**Comment by leif81** [comment]
Ya good question. It's grabbing the `dis-enums-1.1.jar` from Maven Central. I had deployed it that there as part of the original 4.08 release way back in 2013. But you're making me realize, dis-enums was one of the pieces I lost track of when we moved from SourceForge. I wonder now if we should include this Java dis-enums source code in `open-dis-java`.

**Comment by leif81** [comment]
Btw here's the link to it in Maven Central:

http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22edu.nps.moves%22

**Comment by mcgredonps** [comment]
The whole current dis-enum software release is questionable. SISO changed the format of the
XML I used to generate the enums, so the code is kind of obsolete. I THINK
the text used in the enums, like “Entity State” becomes ENTITY_STAT, hasn’t changed.
One can also argue about the rules used to convert the english to a constant.
Maybe I’ll be able to update it to the current XML.


I’m not sure how many people actually use the enums. What do you think of the
Syntax used, with both the numeric value and the text value?

public enum ForceID
{

    OTHER(0, "Other"),
    FRIENDLY(1, "Friendly”),

The idea being you can also retrieve the description, not sure if that’s worthwhile.

You should be thinking of yourself as co-manager here, of course.



On Jul 11, 2017, at 7:06 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


Ya good question. It's grabbing the dis-enums-1.1.jar from Maven Central. I had deployed it that there as part of the original 4.08 release way back in 2013. But you're making me realize, dis-enums was one of the pieces I lost track of when we moved from SourceForge. I wonder now if we should include this Java dis-enums source code in open-dis-java.

**Comment by leif81** [comment]
I currently don't use the dis-enums in my projects, but I really should. More readable code is a good thing.

Ya I think a string version of the enum would be handy.

**Comment by mcgredonps** [comment]
The enums are also useful in other languages, such as C++ and C#. It’s kind of
Classic for some development philosophies. Yeah, worthwhile I suppose. Got a
couple other things I want to work on as well, and getting it all web-friendly seems
like the critical thing.

On Jul 11, 2017, at 7:47 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


I currently don't use the dis-enums in my projects, but I really should. More readable code is a good thing.

Ya I think a string version of the enum would be handy.
