### ISSUE TITLE
Error in deadreckoning.utils Matrix mult method

### ISSUE THREAD

**Issue by camejia** [open-dis/open-dis-java#31]
I have a fix for this issue, but I was unable to submit pull request.  Do I need to be added to a list of users for this project?  (It's possible that I'm not using GitHub correctly; I'm using GitHub desktop.)

As a longer term solution, I'd like to replace the Matrix class in the deadreckoning.utils package with Apache Commons Math.  However, (1) I don't know whether the project owners are OK with introducing this dependency, and (2) I'm don't know the correct way to include this dependency via Maven.  Please advise whether this is a worthwhile update, and if anyone can help with the Maven part.

~Chris

**Comment by leif81** [comment]
Hi Chris,

That's strange, I'm not aware of a setting here that would be preventing pull requests. Once you've forked this repo into your personal space, make your changes on a branch, push it back to your personal fork of the repo, and then open a pull request to have your branch merged into the upstream project here named `open-dis/open-dis-java`. That should work.

As for your question about replacing the Matrix class with a dependency, I'm all for that that idea personally. I think replacing a bunch of (potentially buggy) math with a widely used library is smart. It's very easy to add dependencies with Maven. It's done in the project `pom.xml` file by adding a few lines defining the artifact name and version. If you need further help with that please ask.

**Comment by leif81** [comment]
Fixed in PR #34
