### ISSUE TITLE
Dead Reckoning algorithm RVB 08 linear motion fails

### ISSUE THREAD

**Issue by camejia** [open-dis/open-dis-java#33]
Per the comments in the code: " it is coded up, but the linear motion does not seem to work....rotation works but linear motion fails...not sure why they are calculating the linear motion the way they are..."

I have a Java version of the C code in the Towers & Hines paper referenced at the end of IEEE Std 1278.1-2012.  My Java version passes the two test cases at the end of that paper.  Note that the C code in the Towers & Hines paper (and my Java version of the same) handles all Dead Reckoning algorithms in one function by treating the simpler algorithms as special cases of the more complicated algorithms.

**Comment by leif81** [comment]
Thanks again Chris. Pull requests are welcome!

**Comment by leif81** [comment]
@camejia Was this fixed in your PR #38, or is this still an issue?

**Comment by camejia** [comment]
Umm, I think we should leave this one open.  Re-reading the comment in the original code, it sounds like there is a problem when the angular velocities are all zero.  Unfortunately, I have not yet included a test case for this.  The implementation I adapted from Towers & Hines does attempt to handle this case (though I haven't tested it).  FYI I'm going to be on vacation for a couple of weeks, but may pick up work on this when I return.

**Comment by leif81** [comment]
Closing because of comment seen just now in PR #42 that it fixes this.
