### ISSUE TITLE
DIS_DeadReckoning and concrete classes not thread safe

### ISSUE THREAD

**Issue by camejia** [open-dis/open-dis-java#41]
Per comments on getUpdatedPositionOrientation(): "This function does not actually perform the computations, it only returns the current state of the entity. The entity state is updated by the specified DR algorithm within the DR class behind the scenes. Updates are created every 1/30 seconds."

It is possible for an observer to query the state while the behind the scenes updates are in progress, returning a partially updated inconsistent state.  In my opinion it may not be worthwhile to update this code to make it thread safe; perhaps warning comments should be added regarding this potential issue.

I believe the underlying math that does the updates is correct (both in the DIS_DeadReckoning concrete classes and the unified DeadReckoner implementation) and the thread safety is only an issue when used as described in the quoted comment above.

**Comment by leif81** [comment]
This is a helpful comment @camejia . I have marked the mentioned DR_ classes deprecated, and will leave this issue open as a reminder of the thread safe-ness concern until the classes are removed from the project.

**Comment by leif81** [comment]
The DIS_DeadReckoning class was deprecated in the 5.1 release. Anyone still using this class please try using the DIS_DeadReckoner class instead.
