### ISSUE TITLE
DIS 7 EntityMarking characters should be an array

### ISSUE THREAD

**Issue by bn-dignitas** [open-dis/open-dis-java#43]
The DIS7 EntityMarking characters field should be an 11 byte array, the same as in the DIS 6 Marking class

**Comment by mcgredonps** [comment]
Thanks, for some reason the DIS7 code generated from XML ignored the actual XML syntax asked for.
Basically copied from the DIS6, didn’t do any serious testing but it should work.

On Jul 4, 2017, at 10:35 AM, B. Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


The DIS7 EntityMarking characters field should be an 11 byte array, the same as in the DIS 6 Marking class

**Comment by leif81** [comment]
I think this was fixed in 43a0c023e9b6ae42dc8aba31c1562190ffd156e9

@mcgredonps can you reopen if I'm mistaken.
