### ISSUE TITLE
Drop support for Java 6?

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-java#46]
Currently the library supports being run on JVM's of version 6 or higher. (This is controlled in the `pom.xml` by `maven-compiler-plugin` `source` and `target` fields).

Leaving support for Java 6 may continue to enable the library to be used in some legacy environments (do we know of any users doing this?)

The downside is we can't use any of the new Java 7 or 8 API's.

I'm thinking we should bump the minimum supported version to at least 7.

**Comment by mcgredonps** [comment]
There are some security arguments as well. Oracle apparently supports security updates for
only JDK 8 now.

http://www.oracle.com/technetwork/java/eol-135779.html

"As outlined in the Oracle JDK Support Roadmap<http://www.oracle.com/technetwork/java/eol-135779.html#Java6-end-public-updates>, after April 2015, Oracle will not post further updates of Java SE 7 to its public download sites. “

The compatibility guide:

http://www.oracle.com/technetwork/java/javase/8-compatibility-guide-2156366.html

Apparent 6 to 7 problems?
http://www.oracle.com/technetwork/java/javase/compatibility-417013.html#jdk7

I have no idea what the world is using for Java versions. Any problems using v7 jars
in a v8 app?


On Aug 16, 2017, at 9:34 AM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently the library supports being run on JVM's of version 6 or higher. (This is controlled in the pom.xml by maven-compiler-plugin source and target fields).

Leaving support for Java 6 may continue to enable the library to be used in some legacy environments (do we know of any users doing this?)

The downside is we can't use any of the new Java 7 or 8 API's.

I'm thinking we should bump the minimum supported version to at least 7.

**Comment by leif81** [comment]
As far as I understand it's Ok to use a lower version jar in a higher version JVM. For example I use the open-dis jar built for version 6 in my apps that I run on version 8 JVM and that works fine.

**Comment by mcgredonps** [comment]
I think you’re right.. Plenty of older java 7 engines distributed via yum and apt. Probably safe to move away from JDK 6.

https://plumbr.eu/blog/java/java-version-and-vendor-data-analyzed-2016-edition

[cid:2151C101-BEF0-4A65-92B4-0E2DE029A7EA@hsd1.or.comcast.net]

On Aug 16, 2017, at 12:32 PM, Leif Gruenwoldt <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I understand it's Ok to use a lower version jar in a higher version JVM. For example I use the open-dis jar built for version 6 in my apps that I run on version 8 JVM and that works fine.
