### ISSUE TITLE
Remove code from SourceForge

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-java#52]
Hi Don, should we close down the SourceForge project soon? 

https://sourceforge.net/projects/open-dis/

A fair number of people seem to still be going there and downloading old code and files. I assume they don't know about the GitHub projects and think they are getting the latest content. Is there anything on SourceForge that hasn't been migrated yet to GitHub we'd want to move over first?

**Comment by mcgredonps** [comment]
Yeah, I think it's about time. Probably have to write some introductory README.md that is displayed at the project level.


________________________________

**Comment by leif81** [comment]
@mcgredonps This something I can help with?

**Comment by leif81** [comment]
There is a notice on the sourceforge site saying:

> This project is inactive and has migrated to a GitHub project at https://github.com/open-dis

Closing.
