### ISSUE TITLE
Difference in comments to implementation

### ISSUE THREAD

**Issue by Jonoo97** [open-dis/open-dis-java#55]
Comment says Gets the Euler Theta value (in radians) from position and Tait-Brayn yaw and roll angles but implementation uses pitch not roll public static double getThetaFromTaitBryanAngles(double lat, double lon, double yaw, double pitch). This is the same for getPsiFromTaitBryanAngles. 

https://github.com/open-dis/open-dis-java/blob/d3c2b19aed8e80c5e7ef938dc0982f5ad0282ae6/src/main/java/edu/nps/moves/disutil/EulerConversions.java#L126

**Comment by leif81** [comment]
Thanks @Jonoo97 ! You're welcome to submit a PR if you like.
