### ISSUE TITLE
SISO-REF-010 Updates

### ISSUE THREAD

**Issue by mciccarone** [open-dis/open-dis-java#58]
Hi All,
   I am not able to locate where the SISO-REF-010 triggers the generation of the OpenDIS enumerations files. The version that currently exists in the C# code base (for example) uses the CET2010 entity types, which are slowly getting deprecated. 
 
Does OpenDIS have the capability to auto-generate C++,C#,or Java files based on a new SISO-REF-010.xml/xsd file set? 

If so can anyone point me in the direction of where this auto-generation is performed?

Thanks!

**Comment by leif81** [comment]
@mciccarone we have a branch called `dis-enums` here, take a look, my intent is to get that merged in here.

Is this what you're looking for?

**Comment by mciccarone** [comment]
Hi Leif,
  Are you referring to https://github.com/open-dis/Enumerations ?
 I'm looking at that now and it might do what I need. 

I looked at the Java-Enums but that doesn't appear to generate the source files from the SISO XML file, but that was from a quick look at the code. 
Thanks for the quick response !

**Comment by leif81** [comment]
Yes, the Enumerations repository is the tool used to auto generate code in various languages. The source code in the `dis-enums` branch in this repository was generated using that tool.

Does that answer your question?

**Comment by leif81** [comment]
@mciccarone I'm going to close this one. Feel free to re-open it if we didn't answer your question.
