### ISSUE TITLE
Update Maven Central?

### ISSUE THREAD

**Issue by jmlogan** [open-dis/open-dis-java#63]
I noticed that Maven Central only has up to 4.0.8. Any chance of getting newer versions deployed up there for easier integration?

Thanks!

**Comment by leif81** [comment]
Hi @jmlogan yes it's something I've been meaning to do. Have you tried using the jitpack maven repository? There are instructions in the readme.

**Comment by leif81** [comment]
I cut the 5.0 release the other day and it's now available in Maven Central.

https://search.maven.org/artifact/edu.nps.moves/open-dis/5.0/jar
