### ISSUE TITLE
Absence of edu.nps.moves.disenum in Release 5.0

### ISSUE THREAD

**Issue by SykesSR** [open-dis/open-dis-java#67]
Release 5.0 doesn't compile, because there is a missing package: edu.nps.moves.disenum. Tested using jdk1.8.0_171

**Comment by leif81** [comment]
@SykesSR yes the open-dis package depends on the dis-enums package. 

If you're using Maven specifying open-dis will automatically download the dis-enums package too.

If you're using Ant or something like that you'll need to download the dis-enums package and add it to your classpath. I assume this is your case. I will update the readme, I see this is missing.

https://search.maven.org/remotecontent?filepath=edu/nps/moves/dis-enums/1.1/dis-enums-1.1.jar
