### ISSUE TITLE
A question about CoordinateConversions

### ISSUE THREAD

**Issue by icemagno** [open-dis/open-dis-java#71]
I've made some tests with [CoordinateConversions.java](https://github.com/open-dis/open-dis-java/blob/master/src/main/java/edu/nps/moves/disutil/CoordinateConversions.java) and conclude that I can't take the reverse results correctly.

Example:

```
double[] geods = new double[3];
geods[0] = -23.0;
geods[1] = -45.0;
geods[2] = 0.0;

double[] result = CoordinateConversions.getXYZfromLatLonDegrees(geods[0], geods[1], geods[2]);
// result[0] = 4153622.0304340417
// result[1] = -4153622.030434041
// result[2] = -2476719.3300588187

// Lets reverse the result to prove the formula:
double[] proof = CoordinateConversions.xyzToLatLonDegrees( result );

// proof[0] = -23.000000000000004
// proof[1] = -44.99999999999999
// proof[2] = -9.313225746154785E-10

```
The coordinates error is fine ( a little ) but the elevation is far incorrect and lead to simulation inconsistency ( maybe a collision or ammo hit event).

Is the formula correct?

**Comment by leif81** [comment]
Hi @icemagno 

There is a unit test here that does the round trip check. A small amount of acceptable error had to be identified to get it to pass. I did not see an issue with elevation though in the sample data. Maybe you found a corner case?

https://github.com/open-dis/open-dis-java/blob/master/src/test/java/edu/nps/moves/disutil/CoordinateConversionsTest.java

**Comment by leif81** [comment]
Do you mean this value? -9.313225746154785E-10

That's a very small number right, close to 0.

**Comment by leif81** [comment]
I plugged your values into the unit test in PR #72 and it passed.

Maybe i'm overlooking something, but I think the coordinate conversion is working OK.

**Comment by icemagno** [comment]
Well I think -9 meters is a little far from zero.  In my case I have to simulate airplanes and this may crash someone in land or a mountain. Or just cause a missile to miss the target. 

Im using RPR FOM and data comming from other source as LAT, LON, ALT. So I must convert it to Spatial data (XYZ) and send to RTI. Then I need to get it back to the original values in others federates and this is when I get the different values. So my original source tells me the airplane is landed at zero meters and the federates understand   -9 meters for example.

I've checked others values and the error is different every time. For example there is no error with elevation 10.

My test case was just convert to XYZ and back again to LAT LON ALT using the output values.

The coordinates are ok indeed.

**Comment by leif81** [comment]
Unless I'm misreading the value, the elevation is not -9, it's -0.000000009. It's presented in scientific notation.

**Comment by leif81** [comment]
If you want to be certain, plug your values into the unit test and see if it passes.

**Comment by joshserrin** [comment]
Sounds like your federate code is parsing -9.313225746154785E-10 as -9 instead of -9E-10.  Doesn't appear to be an issue with open-dis.

**Comment by icemagno** [comment]
I see.  Then I think we can close.
