### ISSUE TITLE
Transmitter PDU Variable Parameter Support

### ISSUE THREAD

**Issue by BlueMoose2** [open-dis/open-dis-java#74]
Hi I was wondering when there will be an update to properly support the Variable Parameters on PDUs like the Transmitter PDU? Currently you can get the length, but are unable to get/set these fields. Is there a plan to update this soon or a workaround?

**Comment by leif81** [comment]
Hi @BlueMoose2 
I hadn't thought about the variable params before. I'm using the Transmitter pdu in a project and haven't had a use for sending/receiving variable params yet. If you don't mind me asking, for what purpose do you have for the data in there? And do you have a sample pdu with the data I could use to test an implementation here. Thanks!

**Comment by leif81** [comment]
Transmitter PDU Variable Parameters were recently added in #128 .

@BlueMoose2 I think this will address your original issue here. If not please leave a comment and feel free to reopen the issue.
