### ISSUE TITLE
ElectronicEmissionsPdu dis7 Support

### ISSUE THREAD

**Issue by lcowan94** [open-dis/open-dis-java#75]
Hi, I was wondering if the ElectronicEmissionPdu in dis7 will be fully supported? 
I am in need of getting the beam status from the ElectronicEmissionPdu as in section 7.6.2.2.f.5.ix

**Comment by leif81** [comment]
Hi @lcowan94 

Pull requests are welcome. Would you be interested in submitting a PR for this change?

And could you share a sample pdu to be used here in a junit test to confirm the implementation?

**Comment by lcowan94** [comment]
Hi, I've got an update with some unit tests for you. How do I submit the pull request?

**Comment by leif81** [comment]
Terrific.
There's some good info here on creating pull requests.
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests

**Comment by leif81** [comment]
Thanks again @lcowan94 for the contribution.

I will probably cut a v5.1 release since your change is significant enough. Let me know if that'd be useful for you.
