### ISSUE TITLE
Difference with standard protocol for orientation

### ISSUE THREAD

**Issue by farhan-mirzaaa** [open-dis/open-dis-java#80]
Hi,

I want to ask a question about orientation which is mentioned in "open-dis/open-dis-java/blob/master/src/main/java/edu/nps/moves/deadreckoning/DIS_DeadReckoning.java" at line no. 153. In fact, standard says that psi is the rotation around z axis whereas at above mentioned line number it is written that "the PSI (rotation about the y-axis)". 

Is this deliberate because this will effect calculations?

Regards,
Farhan

**Comment by leif81** [comment]
@farhan-mirzaaa Thank-you for the report. I see what you are referencing on this line:

https://github.com/open-dis/open-dis-java/blob/master/src/main/java/edu/nps/moves/deadreckoning/DIS_DeadReckoning.java#L153

I'm not sure of the answer to your question. Have you looked at the unit test for this class? Does this unit test answer your concern?

https://github.com/open-dis/open-dis-java/blob/master/src/test/java/edu/nps/moves/deadreckoning/DeadReckonerTest.java

**Comment by leif81** [comment]
Correction, I was mistaken. The above referenced unit test is not for the class DIS_DeadReckoning. It is for the DeadReckoner class which is an alternate implementation in the same package path.

Back to your original question. I would suggest if you would be interested to create a unit test for DIS_DeadReckoning to test the implementation and fix up the code and/or comment as neccessary and submit as PR.

**Comment by leif81** [comment]
@farhan-mirzaaa the above mentioned class DIS_DeadReckoning has been marked deprecated in the 5.1 release. I suggest you try the DIS_DeadReckoner class instead and if you have an issue can you please open a new issue.
