### ISSUE TITLE
DeadReckoner:perform_DR() for (some) articulated parts not working

### ISSUE THREAD

**Issue by LumHwang** [open-dis/open-dis-java#86]
We are using articulated parts parameters:
1) Turret Azimuth
    PRIMARY_TURRET_NUMBER_1 + AZIMUTH
2) Gun Elevation (attached to turret)
    PRIMARY_GUN_NUMBER_1 + ELEVATION

When perform_DR() is called on those parts, the values produced for turret Azimuth seem correct at certain angles, but at other angles, the values flip/flop (even when there is no movement).

In the end, I think that dead-reckoning for those parts should be disabled.

**Comment by leif81** [comment]
Thank-you for the report @LumHwang . Will await confirmation the change passed lab testing and then will proceed with merging the PR.
